on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.149.0"
          extended: true

      - name: Build docs
        run: hugo

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2cd52de272eccd3c0c6ab86503c40848
          projectName: autodarts-diy-docs
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
