on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true

      - name: Install dependencies
        run: yarn
      - name: Build docs
        run: hugo

      - name: Get tag
        run: echo "version=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: .docker/Dockerfile
          tags: |
            ghcr.io/autodarts/docs:latest
            ghcr.io/autodarts/docs:${{ env.version }}

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Get tag
        run: echo "version=${{ github.run_id }}" >> $GITHUB_ENV

      - uses: Azure/k8s-deploy@v4
        with:
          namespace: autodarts-web
          manifests: |
            .kubernetes/deployment.yaml
          images: ghcr.io/autodarts/docs:${{ env.version }}
